### ISSUE TITLE
[Bug] build failed / ビルドできない

### ISSUE THREAD

**Issue by Ningensei848** [togostanza/metastanza#30]
When I try to `npx togostanza build`, I get the following error.

It seems to be fixed by setting `preventAssignment` of RollUp to `true`, but I don't know how to fix it ......

---

`npx togostanza build` しようとすると以下のようにエラーが起こります．

RollUp の `preventAssignment` を `true` にすれば直るようなのですが，よくわからず……

---

```shell
@rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
build failure
Unexpected token (2:2) in /buildstage/stanzas/table-with-scroll/app.vue?vue&type=template&id=3678d910&lang.js
        at BuildStanzas
-~- created here: -~-
    at new Plugin (/buildstage/node_modules/broccoli-plugin/dist/index.js:45:33)
    at new BuildStanzas (file:///buildstage/node_modules/togostanza/src/build-stanzas.mjs:21:5)
    at composeTree (file:///buildstage/node_modules/togostanza/src/commands/-build-internal.mjs:96:19)
    at build (file:///buildstage/node_modules/togostanza/src/commands/build.mjs:26:43)
    at Command.<anonymous> (file:///buildstage/node_modules/togostanza/src/commands/build.mjs:16:11)
    at Command.listener [as _actionHandler] (/buildstage/node_modules/togostanza/node_modules/commander/index.js:922:31)
    at Command._parseCommand (/buildstage/node_modules/togostanza/node_modules/commander/index.js:1503:14)
    at Command._dispatchSubcommand (/buildstage/node_modules/togostanza/node_modules/commander/index.js:1443:18)
    at Command._parseCommand (/buildstage/node_modules/togostanza/node_modules/commander/index.js:1460:12)
    at Command.parse (/buildstage/node_modules/togostanza/node_modules/commander/index.js:1292:10)
-~- (end) -~-


Stack Trace and Error Report: /tmp/error.dump.c040898387c3254555490fc097a0a5cc.log
The command '/bin/sh -c npx togostanza build' returned a non-zero code: 1
```

**Comment by ursm** [comment]
おそらく rollup のメッセージは警告で、その下が実際のエラーだと思います。vue のビルドに失敗していますね。
ただ手元の環境では警告もエラーも出ておらず、何か異なる点があるのだと思います。git status を実行したとき package-lock.json に diff が出ていたりはしないでしょうか。

私の環境は以下のようになっています。

```
$ git rev-parse HEAD
0306c3c0ce6d9b25503d080357f1c399d1ab6ba9
$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
$ node --version
v15.3.0
$ npm --version
6.14.11
$ npm ls @rollup/plugin-replace rollup-plugin-vue @vue/compiler-sfc
metastanza@0.0.1 /home/ursm/src/github.com/togostanza/metastanza
├── @rollup/plugin-replace@2.3.4 
├── @vue/compiler-sfc@3.0.5 
├── rollup-plugin-vue@6.0.0-beta.10 
└─┬ togostanza@3.0.0-beta.12
  ├── @rollup/plugin-replace@2.3.4  deduped
  ├── @vue/compiler-sfc@3.0.5  deduped
  └── rollup-plugin-vue@6.0.0-beta.10  deduped
```

この状態でビルドが通ります。

```
$ npx togostanza b
[@vue/compiler-sfc] compileScript now requires passing the `id` option.
Upgrade your vite or vue-loader version for compatibility with the latest experimental proposals.

[@vue/compiler-sfc] compileTemplate now requires the `id` option.`.


Slowest Nodes (totalTime >= 5%)               | Total (avg)         
----------------------------------------------+---------------------
BuildStanzas (1)                              | 11049ms             
BuildPages (1)                                | 2798ms              

Built - 13852 ms @ Fri Mar 05 2021 18:51:51 GMT+0900 (Japan Standard Time)
```
